#include "web_static_pages.h"
#include "esp_log.h"

static const char s_index_html[] = "﻿<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "  <title>ESP32 工业网关边缘管理平台</title>\n"
    "  <link rel=\"stylesheet\" href=\"/style.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <div class=\"container\">\n"
    "    <!-- 头部 Header -->\n"
    "    <header class=\"header\">\n"
    "      <div class=\"header-title\">\n"
    "        <h1>🌐 ESP32 工业网关边缘管理平台</h1>\n"
    "        <p>基于 FreeRTOS + Modbus Master + NVS 配置热重载架构</p>\n"
    "      </div>\n"
    "      <div class=\"header-badges\">\n"
    "        <span class=\"badge badge-ok\" id=\"header-wifi-badge\">WiFi: 连接中...</span>\n"
    "        <span class=\"badge badge-ok\" id=\"header-mqtt-badge\">MQTT: 连接中...</span>\n"
    "        <span class=\"badge\" id=\"header-uptime-badge\">运行: 00:00:00</span>\n"
    "      </div>\n"
    "    </header>\n"
    "\n"
    "    <!-- 选项卡 Tabs -->\n"
    "    <nav class=\"tabs\">\n"
    "      <button class=\"tab-btn active\" data-tab=\"dashboard\">📊 实时监控</button>\n"
    "      <button class=\"tab-btn\" data-tab=\"config\">⚙️ 设备配置管理</button>\n"
    "      <button class=\"tab-btn\" data-tab=\"status\">ℹ️ 系统状态</button>\n"
    "    </nav>\n"
    "\n"
    "    <!-- Tab 1: 实时监控 Dashboard -->\n"
    "    <section id=\"tab-dashboard\" class=\"tab-panel active\">\n"
    "      <div style=\"display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;\">\n"
    "        <h2 style=\"font-size:16px;color:var(--text-muted);\">● Modbus 现场总线实时遥测与数字孪生快照 (1.5s 自动刷新)</h2>\n"
    "        <button class=\"btn btn-secondary btn-sm\" onclick=\"refreshTelemetrySnapshot()\">⟳ 立即刷新</button>\n"
    "      </div>\n"
    "      <div class=\"grid\" id=\"telemetry-cards-container\">\n"
    "        <div class=\"card\" style=\"grid-column:1/-1;text-align:center;color:var(--text-muted);padding:32px;\">\n"
    "          ⏳ 正在加载现场设备遥测数据...\n"
    "        </div>\n"
    "      </div>\n"
    "    </section>\n"
    "\n"
    "    <!-- Tab 2: 设备配置管理 Config Manager -->\n"
    "    <section id=\"tab-config\" class=\"tab-panel\">\n"
    "      <div style=\"display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;flex-wrap:wrap;gap:10px;\">\n"
    "        <div>\n"
    "          <h2 style=\"font-size:16px;color:var(--text-main);display:inline;\">Modbus 从站采集节点配置表</h2>\n"
    "          <span class=\"badge badge-ok\" id=\"config-version-badge\" style=\"margin-left:8px;\">v1</span>\n"
    "        </div>\n"
    "        <div style=\"display:flex;gap:8px;\">\n"
    "          <button class=\"btn btn-primary\" onclick=\"openAddDeviceModal()\">➕ 添加 Modbus 设备</button>\n"
    "          <button class=\"btn btn-secondary\" onclick=\"loadAndRenderConfigTable()\">⟳ 刷新配置</button>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"table-container\">\n"
    "        <table>\n"
    "          <thead>\n"
    "            <tr>\n"
    "              <th>设备名称</th>\n"
    "              <th>从站 ID</th>\n"
    "              <th>采集寄存器与类型</th>\n"
    "              <th>数据类型 (倍率)</th>\n"
    "              <th>采样周期</th>\n"
    "              <th>操作</th>\n"
    "            </tr>\n"
    "          </thead>\n"
    "          <tbody id=\"config-table-body\">\n"
    "            <tr>\n"
    "              <td colspan=\"6\" style=\"text-align:center;color:var(--text-muted);padding:24px;\">⏳ 正在读取 NVS 与 RAM 运行态配置...</td>\n"
    "            </tr>\n"
    "          </tbody>\n"
    "        </table>\n"
    "      </div>\n"
    "    </section>\n"
    "\n"
    "    <!-- Tab 3: 系统状态 System Status -->\n"
    "    <section id=\"tab-status\" class=\"tab-panel\">\n"
    "      <div class=\"grid\">\n"
    "        <div class=\"card\">\n"
    "          <div class=\"card-header\">\n"
    "            <h2>网关核心硬件与固件</h2>\n"
    "          </div>\n"
    "          <div class=\"metric-row\"><span class=\"metric-name\">网关唯一标识 (ID)</span><span class=\"metric-val\" id=\"stat-gw-id\">--</span></div>\n"
    "          <div class=\"metric-row\"><span class=\"metric-name\">固件固化版本</span><span class=\"metric-val\" id=\"stat-fw-ver\">--</span></div>\n"
    "          <div class=\"metric-row\"><span class=\"metric-name\">NVS 配置生效版本</span><span class=\"metric-val\" id=\"stat-cfg-ver\">--</span></div>\n"
    "          <div class=\"metric-row\"><span class=\"metric-name\">系统持续运行时间</span><span class=\"metric-val\" id=\"stat-uptime\">--</span></div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"card\">\n"
    "          <div class=\"card-header\">\n"
    "            <h2>内存与网络连接状态</h2>\n"
    "          </div>\n"
    "          <div class=\"metric-row\"><span class=\"metric-name\">动态堆内存 (Free Heap)</span><span class=\"metric-val\" id=\"stat-heap\">--</span></div>\n"
    "          <div class=\"metric-row\"><span class=\"metric-name\">WiFi 连接状态 (STA)</span><span class=\"metric-val\" id=\"stat-wifi\">--</span></div>\n"
    "          <div class=\"metric-row\"><span class=\"metric-name\">MQTT 物模型出口</span><span class=\"metric-val\" id=\"stat-mqtt\">--</span></div>\n"
    "          <div class=\"metric-row\"><span class=\"metric-name\">FreeRTOS 调度器</span><span class=\"metric-val\">🟢 运行中</span></div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </section>\n"
    "  </div>\n"
    "\n"
    "  <!-- 添加 / 编辑设备弹窗 Modal -->\n"
    "  <div class=\"modal-overlay\" id=\"device-modal\">\n"
    "    <div class=\"modal-box\">\n"
    "      <h2 class=\"modal-title\" id=\"modal-device-title\">➕ 添加 Modbus 设备</h2>\n"
    "      \n"
    "      <div class=\"form-group\">\n"
    "        <label class=\"form-label\">设备标识名称 (唯一 Name)</label>\n"
    "        <input type=\"text\" id=\"dev-form-name\" class=\"form-control\" placeholder=\"例如: pressure_sensor_v2\">\n"
    "      </div>\n"
    "\n"
    "      <div class=\"form-row\">\n"
    "        <div class=\"form-group\">\n"
    "          <label class=\"form-label\">从站地址 (Slave ID: 1~247)</label>\n"
    "          <input type=\"number\" id=\"dev-form-slave\" class=\"form-control\" min=\"1\" max=\"247\" value=\"2\">\n"
    "        </div>\n"
    "        <div class=\"form-group\">\n"
    "          <label class=\"form-label\">采集周期 (Period: 50~60000 ms)</label>\n"
    "          <input type=\"number\" id=\"dev-form-period\" class=\"form-control\" min=\"50\" max=\"60000\" step=\"50\" value=\"1000\">\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"form-row\">\n"
    "        <div class=\"form-group\">\n"
    "          <label class=\"form-label\">寄存器起始地址 (0~65535)</label>\n"
    "          <input type=\"number\" id=\"dev-form-addr\" class=\"form-control\" min=\"0\" max=\"65535\" value=\"16\">\n"
    "        </div>\n"
    "        <div class=\"form-group\">\n"
    "          <label class=\"form-label\">寄存器类型 (Register Type)</label>\n"
    "          <select id=\"dev-form-regtype\" class=\"form-control\">\n"
    "            <option value=\"holding\">Holding Register (保持寄存器 0x03)</option>\n"
    "            <option value=\"input\">Input Register (输入寄存器 0x04)</option>\n"
    "          </select>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"form-row\">\n"
    "        <div class=\"form-group\">\n"
    "          <label class=\"form-label\">数据类型 (Data Type)</label>\n"
    "          <select id=\"dev-form-datatype\" class=\"form-control\">\n"
    "            <option value=\"uint16\">uint16 (无符号 16位)</option>\n"
    "            <option value=\"int16\">int16 (有符号 16位)</option>\n"
    "            <option value=\"float\">float (32位 浮点数)</option>\n"
    "          </select>\n"
    "        </div>\n"
    "        <div class=\"form-group\">\n"
    "          <label class=\"form-label\">换算倍率 (Scale)</label>\n"
    "          <input type=\"number\" id=\"dev-form-scale\" class=\"form-control\" step=\"0.001\" value=\"0.1\">\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <div id=\"check-result-box\" style=\"margin-top:12px;padding:10px;border-radius:6px;background:#162032;border:1px solid var(--border-color);font-size:13px;display:none;\"></div>\n"
    "\n"
    "      <div class=\"modal-actions\">\n"
    "        <button class=\"btn btn-secondary\" onclick=\"closeDeviceModal()\">取消</button>\n"
    "        <button class=\"btn btn-secondary\" onclick=\"onTestConfigClick()\" style=\"border:1px solid var(--accent-cyan);color:var(--accent-cyan);\">🧪 测试配置 (Check)</button>\n"
    "        <button class=\"btn btn-primary\" onclick=\"onSaveConfigClick()\">💾 保存并应用 (Apply)</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- 删除确认弹窗 Modal -->\n"
    "  <div class=\"modal-overlay\" id=\"delete-modal\">\n"
    "    <div class=\"modal-box\" style=\"max-width:400px;\">\n"
    "      <h2 class=\"modal-title\" style=\"color:var(--accent-rose);\">⚠️ 确认删除设备</h2>\n"
    "      <p style=\"color:var(--text-muted);font-size:14px;margin-bottom:20px;\">\n"
    "        确定要从网关中删除设备 <strong id=\"delete-target-name\" style=\"color:#fff;\"></strong> 吗？<br><br>\n"
    "        删除后调度器将立即平滑停止该节点的 Modbus 采集，并同步从 NVS 持久化存储中移除。\n"
    "      </p>\n"
    "      <div class=\"modal-actions\">\n"
    "        <button class=\"btn btn-secondary\" onclick=\"closeDeleteModal()\">取消</button>\n"
    "        <button class=\"btn btn-danger\" onclick=\"onConfirmDeleteDevice()\">确认删除</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- 全局 Toast 提示 -->\n"
    "  <div class=\"alert-toast\" id=\"alert-toast\"></div>\n"
    "\n"
    "  <!-- 脚本加载 -->\n"
    "  <script src=\"/api.js\"></script>\n"
    "  <script src=\"/config_editor.js\"></script>\n"
    "  <script src=\"/app.js\"></script>\n"
    "</body>\n"
    "</html>\n"
    "";
static const char s_style_css[] = "﻿/* ========================================================================= */\n"
    "/*                   ESP32 工业网关 UI 现代化深色工业样式表                  */\n"
    "/* ========================================================================= */\n"
    ":root {\n"
    "  --bg-main: #0f172a;\n"
    "  --bg-card: #1e293b;\n"
    "  --bg-card-hover: #243248;\n"
    "  --bg-input: #0f172a;\n"
    "  --border-color: #334155;\n"
    "  --text-main: #f8fafc;\n"
    "  --text-muted: #94a3b8;\n"
    "  --accent-cyan: #38bdf8;\n"
    "  --accent-cyan-hover: #0ea5e9;\n"
    "  --accent-emerald: #10b981;\n"
    "  --accent-amber: #f59e0b;\n"
    "  --accent-rose: #f43f5e;\n"
    "}\n"
    "\n"
    "* { box-sizing: border-box; margin: 0; padding: 0; }\n"
    "body {\n"
    "  font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;\n"
    "  background: var(--bg-main);\n"
    "  color: var(--text-main);\n"
    "  line-height: 1.5;\n"
    "  padding: 20px;\n"
    "}\n"
    "\n"
    ".container { max-width: 1100px; margin: 0 auto; }\n"
    "\n"
    "/* 头部 Header */\n"
    ".header {\n"
    "  display: flex;\n"
    "  justify-content: space-between;\n"
    "  align-items: center;\n"
    "  flex-wrap: wrap;\n"
    "  gap: 12px;\n"
    "  padding-bottom: 16px;\n"
    "  border-bottom: 1px solid var(--border-color);\n"
    "  margin-bottom: 20px;\n"
    "}\n"
    ".header-title h1 { font-size: 22px; color: var(--accent-cyan); display: flex; align-items: center; gap: 8px; }\n"
    ".header-title p { font-size: 13px; color: var(--text-muted); }\n"
    ".header-badges { display: flex; gap: 8px; align-items: center; }\n"
    "\n"
    "/* 标签徽章 Badges */\n"
    ".badge {\n"
    "  display: inline-flex;\n"
    "  align-items: center;\n"
    "  gap: 4px;\n"
    "  padding: 3px 10px;\n"
    "  border-radius: 9999px;\n"
    "  font-size: 12px;\n"
    "  font-weight: 600;\n"
    "  background: #334155;\n"
    "  color: #e2e8f0;\n"
    "}\n"
    ".badge-ok { background: rgba(16, 185, 129, 0.2); color: #34d399; border: 1px solid rgba(16, 185, 129, 0.4); }\n"
    ".badge-warn { background: rgba(245, 158, 11, 0.2); color: #fbbf24; border: 1px solid rgba(245, 158, 11, 0.4); }\n"
    ".badge-err { background: rgba(244, 63, 94, 0.2); color: #fb7185; border: 1px solid rgba(244, 63, 94, 0.4); }\n"
    "\n"
    "/* 导航栏 Tabs */\n"
    ".tabs {\n"
    "  display: flex;\n"
    "  gap: 8px;\n"
    "  margin-bottom: 20px;\n"
    "  background: var(--bg-card);\n"
    "  padding: 4px;\n"
    "  border-radius: 8px;\n"
    "  border: 1px solid var(--border-color);\n"
    "}\n"
    ".tab-btn {\n"
    "  flex: 1;\n"
    "  background: transparent;\n"
    "  border: none;\n"
    "  color: var(--text-muted);\n"
    "  font-size: 14px;\n"
    "  font-weight: 600;\n"
    "  padding: 10px 16px;\n"
    "  border-radius: 6px;\n"
    "  cursor: pointer;\n"
    "  transition: all 0.2s;\n"
    "  text-align: center;\n"
    "}\n"
    ".tab-btn:hover { color: var(--text-main); background: rgba(255,255,255,0.05); }\n"
    ".tab-btn.active {\n"
    "  background: var(--accent-cyan);\n"
    "  color: #0f172a;\n"
    "}\n"
    "\n"
    "/* 面板内容 Panels */\n"
    ".tab-panel { display: none; }\n"
    ".tab-panel.active { display: block; animation: fadeIn 0.2s ease-in; }\n"
    "@keyframes fadeIn { from { opacity: 0; transform: translateY(4px); } to { opacity: 1; transform: translateY(0); } }\n"
    "\n"
    "/* 网格与卡片 Cards */\n"
    ".grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 16px; margin-bottom: 20px; }\n"
    ".card {\n"
    "  background: var(--bg-card);\n"
    "  border-radius: 10px;\n"
    "  padding: 20px;\n"
    "  border: 1px solid var(--border-color);\n"
    "  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.2);\n"
    "}\n"
    ".card-header {\n"
    "  display: flex;\n"
    "  justify-content: space-between;\n"
    "  align-items: center;\n"
    "  margin-bottom: 14px;\n"
    "  padding-bottom: 10px;\n"
    "  border-bottom: 1px solid var(--border-color);\n"
    "}\n"
    ".card-header h2 { font-size: 16px; color: #e2e8f0; font-weight: 600; }\n"
    "\n"
    "/* 遥测数据行 */\n"
    ".metric-row {\n"
    "  display: flex;\n"
    "  justify-content: space-between;\n"
    "  align-items: center;\n"
    "  padding: 8px 0;\n"
    "  border-bottom: 1px solid rgba(51, 65, 85, 0.5);\n"
    "  font-size: 14px;\n"
    "}\n"
    ".metric-row:last-child { border-bottom: none; }\n"
    ".metric-name { color: var(--text-muted); }\n"
    ".metric-val { color: var(--accent-cyan); font-weight: 700; font-family: monospace; font-size: 16px; }\n"
    "\n"
    "/* 表格 Table */\n"
    ".table-container { overflow-x: auto; background: var(--bg-card); border-radius: 8px; border: 1px solid var(--border-color); }\n"
    "table { width: 100%; border-collapse: collapse; text-align: left; font-size: 14px; }\n"
    "th, td { padding: 12px 16px; border-bottom: 1px solid var(--border-color); }\n"
    "th { background: #162032; color: var(--text-muted); font-weight: 600; }\n"
    "tr:last-child td { border-bottom: none; }\n"
    "tr:hover td { background: var(--bg-card-hover); }\n"
    "\n"
    "/* 按钮 Buttons */\n"
    ".btn {\n"
    "  display: inline-flex;\n"
    "  align-items: center;\n"
    "  justify-content: center;\n"
    "  gap: 6px;\n"
    "  padding: 8px 14px;\n"
    "  font-size: 13px;\n"
    "  font-weight: 600;\n"
    "  border-radius: 6px;\n"
    "  border: none;\n"
    "  cursor: pointer;\n"
    "  transition: all 0.2s;\n"
    "}\n"
    ".btn-primary { background: var(--accent-cyan); color: #0f172a; }\n"
    ".btn-primary:hover { background: var(--accent-cyan-hover); }\n"
    ".btn-success { background: var(--accent-emerald); color: #fff; }\n"
    ".btn-success:hover { background: #059669; }\n"
    ".btn-danger { background: rgba(244, 63, 94, 0.15); color: #fb7185; border: 1px solid rgba(244, 63, 94, 0.3); }\n"
    ".btn-danger:hover { background: rgba(244, 63, 94, 0.3); }\n"
    ".btn-secondary { background: #334155; color: #f8fafc; }\n"
    ".btn-secondary:hover { background: #475569; }\n"
    ".btn-sm { padding: 4px 8px; font-size: 12px; }\n"
    "\n"
    "/* 弹窗 Modal */\n"
    ".modal-overlay {\n"
    "  display: none;\n"
    "  position: fixed;\n"
    "  top: 0; left: 0; right: 0; bottom: 0;\n"
    "  background: rgba(0, 0, 0, 0.7);\n"
    "  backdrop-filter: blur(4px);\n"
    "  z-index: 1000;\n"
    "  align-items: center;\n"
    "  justify-content: center;\n"
    "  padding: 20px;\n"
    "}\n"
    ".modal-overlay.active { display: flex; animation: fadeIn 0.15s ease-out; }\n"
    ".modal-box {\n"
    "  background: var(--bg-card);\n"
    "  border: 1px solid var(--border-color);\n"
    "  border-radius: 12px;\n"
    "  width: 100%;\n"
    "  max-width: 520px;\n"
    "  padding: 24px;\n"
    "  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.5);\n"
    "}\n"
    ".modal-title { font-size: 18px; color: var(--accent-cyan); margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid var(--border-color); }\n"
    ".form-group { margin-bottom: 14px; }\n"
    ".form-label { display: block; font-size: 13px; color: var(--text-muted); margin-bottom: 6px; font-weight: 500; }\n"
    ".form-control {\n"
    "  width: 100%;\n"
    "  padding: 9px 12px;\n"
    "  background: var(--bg-input);\n"
    "  border: 1px solid var(--border-color);\n"
    "  border-radius: 6px;\n"
    "  color: var(--text-main);\n"
    "  font-size: 14px;\n"
    "  outline: none;\n"
    "  transition: border-color 0.2s;\n"
    "}\n"
    ".form-control:focus { border-color: var(--accent-cyan); }\n"
    ".form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }\n"
    ".modal-actions { display: flex; justify-content: flex-end; gap: 10px; margin-top: 20px; }\n"
    "\n"
    "/* 通知条 Alert */\n"
    ".alert-toast {\n"
    "  position: fixed;\n"
    "  bottom: 24px;\n"
    "  right: 24px;\n"
    "  padding: 12px 20px;\n"
    "  border-radius: 8px;\n"
    "  font-size: 14px;\n"
    "  font-weight: 500;\n"
    "  box-shadow: 0 10px 15px -3px rgba(0,0,0,0.4);\n"
    "  z-index: 2000;\n"
    "  display: none;\n"
    "}\n"
    ".alert-toast.active { display: block; animation: slideUp 0.3s ease-out; }\n"
    "@keyframes slideUp { from { transform: translateY(20px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }\n"
    "";
static const char s_api_js[] = "﻿/**\n"
    " * ============================================================================\n"
    " * ESP32 工业网关统一 REST API 客户端封装 (api.js)\n"
    " * 现场工程师页面与 ESP32 核心后端的数据桥梁\n"
    " * ============================================================================\n"
    " */\n"
    "const GatewayAPI = {\n"
    "  // 1. 获取网关当前运行设备配置\n"
    "  async getConfig() {\n"
    "    const resp = await fetch('/api/v1/config');\n"
    "    if (!resp.ok) throw new Error('HTTP ' + resp.status);\n"
    "    return await resp.json();\n"
    "  },\n"
    "\n"
    "  // 2. Dry-run 配置预校验 (仅测试，不写 NVS，不修改运行态)\n"
    "  async checkConfig(data) {\n"
    "    const resp = await fetch('/api/v1/config/check', {\n"
    "      method: 'POST',\n"
    "      headers: { 'Content-Type': 'application/json' },\n"
    "      body: JSON.stringify(data)\n"
    "    });\n"
    "    return await resp.json();\n"
    "  },\n"
    "\n"
    "  // 3. 配置热应用与 NVS 持久化\n"
    "  async applyConfig(data) {\n"
    "    const resp = await fetch('/api/v1/config/apply', {\n"
    "      method: 'POST',\n"
    "      headers: { 'Content-Type': 'application/json' },\n"
    "      body: JSON.stringify(data)\n"
    "    });\n"
    "    return await resp.json();\n"
    "  },\n"
    "\n"
    "  // 4. 删除指定设备\n"
    "  async removeDevice(deviceName) {\n"
    "    const resp = await fetch('/api/v1/device/remove', {\n"
    "      method: 'POST',\n"
    "      headers: { 'Content-Type': 'application/json' },\n"
    "      body: JSON.stringify({ name: deviceName })\n"
    "    });\n"
    "    return await resp.json();\n"
    "  },\n"
    "\n"
    "  // 5. 获取网关实时遥测与数字孪生快照\n"
    "  async getSnapshot() {\n"
    "    const resp = await fetch('/api/v1/data/snapshot');\n"
    "    if (!resp.ok) throw new Error('HTTP ' + resp.status);\n"
    "    return await resp.json();\n"
    "  },\n"
    "\n"
    "  // 6. 获取网关系统状态 (内存/WiFi/MQTT/Uptime)\n"
    "  async getStatus() {\n"
    "    const resp = await fetch('/api/v1/system/status');\n"
    "    if (!resp.ok) throw new Error('HTTP ' + resp.status);\n"
    "    return await resp.json();\n"
    "  }\n"
    "};\n"
    "window.GatewayAPI = GatewayAPI;\n"
    "";
static const char s_config_editor_js[] = "﻿/**\n"
    " * ============================================================================\n"
    " * ESP32 工业网关设备配置编辑器 (config_editor.js)\n"
    " * 负责设备配置表渲染、增删改表单弹窗、Check -> Apply 完整闭环\n"
    " * ============================================================================\n"
    " */\n"
    "\n"
    "let g_currentConfig = { version: 1, devices: [] };\n"
    "let g_editingDeviceIndex = -1; // -1 表示新增，>=0 表示编辑现有设备\n"
    "\n"
    "// 1. 加载并渲染设备配置表格\n"
    "async function loadAndRenderConfigTable() {\n"
    "  const tbody = document.getElementById('config-table-body');\n"
    "  if (!tbody) return;\n"
    "  \n"
    "  try {\n"
    "    const res = await GatewayAPI.getConfig();\n"
    "    g_currentConfig = res;\n"
    "    \n"
    "    // 更新版本标签\n"
    "    const verBadge = document.getElementById('config-version-badge');\n"
    "    if (verBadge) verBadge.textContent = 'v' + (res.version || 1);\n"
    "    \n"
    "    tbody.innerHTML = '';\n"
    "    const devices = res.devices || [];\n"
    "    \n"
    "    if (devices.length === 0) {\n"
    "      tbody.innerHTML = '<tr><td colspan=\\\"6\\\" style=\\\"text-align:center;color:var(--text-muted);padding:24px;\\\">暂无配置设备，请点击上方按钮添加</td></tr>';\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    devices.forEach((dev, idx) => {\n"
    "      const tr = document.createElement('tr');\n"
    "      const regType = (dev.register && dev.register.type) ? dev.register.type : (dev.reg_type || 'holding');\n"
    "      const regAddr = (dev.register && dev.register.address !== undefined) ? dev.register.address : (dev.address || dev.register_addr || 0);\n"
    "      const dataType = (dev.data && dev.data.type) ? dev.data.type : (dev.data_type || 'uint16');\n"
    "      const scale = (dev.data && dev.data.scale !== undefined) ? dev.data.scale : (dev.scale || 1.0);\n"
    "      const period = dev.period || 1000;\n"
    "\n"
    "      tr.innerHTML = \n"
    "        '<td><strong style=\\\"color:var(--text-main);\\\">' + dev.name + '</strong></td>' +\n"
    "        '<td><span class=\\\"badge\\\">' + dev.slave_id + '</span></td>' +\n"
    "        '<td><code style=\\\"color:var(--accent-cyan);\\\">0x' + regAddr.toString(16).toUpperCase().padStart(4, '0') + ' (' + regAddr + ')</code> <span style=\\\"color:var(--text-muted);font-size:12px;\\\">[' + regType + ']</span></td>' +\n"
    "        '<td>' + dataType + ' (x' + scale + ')</td>' +\n"
    "        '<td>' + period + ' ms</td>' +\n"
    "        '<td>' +\n"
    "          '<button class=\\\"btn btn-secondary btn-sm\\\" onclick=\\\"openEditDeviceModal(' + idx + ')\\\" style=\\\"margin-right:6px;\\\">编辑</button>' +\n"
    "          '<button class=\\\"btn btn-danger btn-sm\\\" onclick=\\\"openDeleteDeviceModal(\\'' + dev.name + '\\')\\\">删除</button>' +\n"
    "        '</td>';\n"
    "      tbody.appendChild(tr);\n"
    "    });\n"
    "  } catch (err) {\n"
    "    console.error('加载配置失败:', err);\n"
    "    showToast('❌ 加载设备配置失败: ' + err.message, 'err');\n"
    "  }\n"
    "}\n"
    "\n"
    "// 2. 打开添加设备弹窗\n"
    "function openAddDeviceModal() {\n"
    "  g_editingDeviceIndex = -1;\n"
    "  document.getElementById('modal-device-title').textContent = '➕ 添加 Modbus 设备';\n"
    "  document.getElementById('dev-form-name').value = '';\n"
    "  document.getElementById('dev-form-name').disabled = false;\n"
    "  document.getElementById('dev-form-slave').value = '2';\n"
    "  document.getElementById('dev-form-addr').value = '16';\n"
    "  document.getElementById('dev-form-regtype').value = 'holding';\n"
    "  document.getElementById('dev-form-datatype').value = 'uint16';\n"
    "  document.getElementById('dev-form-scale').value = '0.1';\n"
    "  document.getElementById('dev-form-period').value = '1000';\n"
    "  document.getElementById('check-result-box').style.display = 'none';\n"
    "\n"
    "  document.getElementById('device-modal').classList.add('active');\n"
    "}\n"
    "\n"
    "// 3. 打开编辑设备弹窗\n"
    "function openEditDeviceModal(idx) {\n"
    "  g_editingDeviceIndex = idx;\n"
    "  const dev = g_currentConfig.devices[idx];\n"
    "  if (!dev) return;\n"
    "\n"
    "  const regType = (dev.register && dev.register.type) ? dev.register.type : (dev.reg_type || 'holding');\n"
    "  const regAddr = (dev.register && dev.register.address !== undefined) ? dev.register.address : (dev.address || dev.register_addr || 0);\n"
    "  const dataType = (dev.data && dev.data.type) ? dev.data.type : (dev.data_type || 'uint16');\n"
    "  const scale = (dev.data && dev.data.scale !== undefined) ? dev.data.scale : (dev.scale || 1.0);\n"
    "  const period = dev.period || 1000;\n"
    "\n"
    "  document.getElementById('modal-device-title').textContent = '✏️ 编辑 Modbus 设备: ' + dev.name;\n"
    "  document.getElementById('dev-form-name').value = dev.name;\n"
    "  document.getElementById('dev-form-name').disabled = true; // 设备名称不可更改\n"
    "  document.getElementById('dev-form-slave').value = dev.slave_id;\n"
    "  document.getElementById('dev-form-addr').value = regAddr;\n"
    "  document.getElementById('dev-form-regtype').value = regType;\n"
    "  document.getElementById('dev-form-datatype').value = dataType;\n"
    "  document.getElementById('dev-form-scale').value = scale;\n"
    "  document.getElementById('dev-form-period').value = period;\n"
    "  document.getElementById('check-result-box').style.display = 'none';\n"
    "\n"
    "  document.getElementById('device-modal').classList.add('active');\n"
    "}\n"
    "\n"
    "// 4. 关闭弹窗\n"
    "function closeDeviceModal() {\n"
    "  document.getElementById('device-modal').classList.remove('active');\n"
    "}\n"
    "\n"
    "// 5. 提取表单数据并构造全局待提交 JSON\n"
    "function buildPayloadFromForm() {\n"
    "  const name = document.getElementById('dev-form-name').value.trim();\n"
    "  const slave_id = parseInt(document.getElementById('dev-form-slave').value, 10);\n"
    "  const address = parseInt(document.getElementById('dev-form-addr').value, 10);\n"
    "  const reg_type = document.getElementById('dev-form-regtype').value;\n"
    "  const data_type = document.getElementById('dev-form-datatype').value;\n"
    "  const scale = parseFloat(document.getElementById('dev-form-scale').value);\n"
    "  const period = parseInt(document.getElementById('dev-form-period').value, 10);\n"
    "\n"
    "  if (!name) throw new Error('设备名称不能为空');\n"
    "  if (isNaN(slave_id) || slave_id < 1 || slave_id > 247) throw new Error('从站 ID 必须在 1 ~ 247 之间');\n"
    "  if (isNaN(address) || address < 0 || address > 65535) throw new Error('寄存器地址必须在 0 ~ 65535 之间');\n"
    "  if (isNaN(period) || period < 50 || period > 60000) throw new Error('采样周期必须在 50 ~ 60000 ms 之间');\n"
    "\n"
    "  const targetDev = {\n"
    "    name: name,\n"
    "    slave_id: slave_id,\n"
    "    register: { address: address, type: reg_type },\n"
    "    data: { type: data_type, scale: isNaN(scale) ? 1.0 : scale },\n"
    "    period: period\n"
    "  };\n"
    "\n"
    "  // 克隆现有配置列表\n"
    "  let newDevices = JSON.parse(JSON.stringify(g_currentConfig.devices || []));\n"
    "\n"
    "  if (g_editingDeviceIndex >= 0) {\n"
    "    // 编辑现有设备\n"
    "    newDevices[g_editingDeviceIndex] = targetDev;\n"
    "  } else {\n"
    "    // 新增设备：检查是否重名\n"
    "    const dup = newDevices.find(d => d.name === name);\n"
    "    if (dup) throw new Error('已存在同名设备 [' + name + ']');\n"
    "    newDevices.push(targetDev);\n"
    "  }\n"
    "\n"
    "  return {\n"
    "    version: (g_currentConfig.version || 1) + 1,\n"
    "    devices: newDevices\n"
    "  };\n"
    "}\n"
    "\n"
    "// 6. 执行 Dry-run 预校验 (测试配置)\n"
    "async function onTestConfigClick() {\n"
    "  const resBox = document.getElementById('check-result-box');\n"
    "  resBox.style.display = 'block';\n"
    "  resBox.innerHTML = '<span style=\\\"color:var(--text-muted);\\\">⏳ 正在向 ESP32 提交 Dry-run 预校验...</span>';\n"
    "\n"
    "  try {\n"
    "    const payload = buildPayloadFromForm();\n"
    "    const res = await GatewayAPI.checkConfig(payload);\n"
    "    if (res.code === 0) {\n"
    "      resBox.innerHTML = '<span style=\\\"color:#34d399;font-weight:600;\\\">✅ Dry-run 校验通过！参数全部合法，可安全应用。</span>';\n"
    "    } else {\n"
    "      resBox.innerHTML = '<span style=\\\"color:#fb7185;font-weight:600;\\\">❌ 校验被拒绝: ' + (res.message || '未知错误') + ' (目标: ' + (res.error_target || '全局') + ')</span>';\n"
    "    }\n"
    "  } catch (err) {\n"
    "    resBox.innerHTML = '<span style=\\\"color:#fb7185;font-weight:600;\\\">❌ 校验错误: ' + err.message + '</span>';\n"
    "  }\n"
    "}\n"
    "\n"
    "// 7. 保存并应用配置 (严格遵循 Check -> Apply 闭环)\n"
    "async function onSaveConfigClick() {\n"
    "  const resBox = document.getElementById('check-result-box');\n"
    "  resBox.style.display = 'block';\n"
    "  resBox.innerHTML = '<span style=\\\"color:var(--text-muted);\\\">⏳ 正在校验并热应用至 ESP32...</span>';\n"
    "\n"
    "  try {\n"
    "    const payload = buildPayloadFromForm();\n"
    "\n"
    "    // 阶段 1: 必须先通过 Check 校验\n"
    "    const checkRes = await GatewayAPI.checkConfig(payload);\n"
    "    if (checkRes.code !== 0) {\n"
    "      resBox.innerHTML = '<span style=\\\"color:#fb7185;font-weight:600;\\\">❌ 校验失败，已终止应用: ' + checkRes.message + '</span>';\n"
    "      showToast('❌ 配置校验失败: ' + checkRes.message, 'err');\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    // 阶段 2: 校验通过，执行 Apply\n"
    "    const applyRes = await GatewayAPI.applyConfig(payload);\n"
    "    if (applyRes.code === 0) {\n"
    "      showToast('✅ 配置热应用成功! 生效版本: v' + applyRes.version + ', 活跃设备: ' + applyRes.device_count, 'ok');\n"
    "      closeDeviceModal();\n"
    "      await loadAndRenderConfigTable();\n"
    "    } else {\n"
    "      resBox.innerHTML = '<span style=\\\"color:#fb7185;font-weight:600;\\\">❌ 应用失败: ' + applyRes.message + '</span>';\n"
    "      showToast('❌ 应用失败: ' + applyRes.message, 'err');\n"
    "    }\n"
    "  } catch (err) {\n"
    "    resBox.innerHTML = '<span style=\\\"color:#fb7185;font-weight:600;\\\">❌ 错误: ' + err.message + '</span>';\n"
    "    showToast('❌ 错误: ' + err.message, 'err');\n"
    "  }\n"
    "}\n"
    "\n"
    "// 8. 打开删除确认弹窗\n"
    "let g_deviceNameToDelete = '';\n"
    "function openDeleteDeviceModal(name) {\n"
    "  g_deviceNameToDelete = name;\n"
    "  document.getElementById('delete-target-name').textContent = name;\n"
    "  document.getElementById('delete-modal').classList.add('active');\n"
    "}\n"
    "\n"
    "function closeDeleteModal() {\n"
    "  document.getElementById('delete-modal').classList.remove('active');\n"
    "}\n"
    "\n"
    "// 9. 确认删除设备\n"
    "async function onConfirmDeleteDevice() {\n"
    "  if (!g_deviceNameToDelete) return;\n"
    "  try {\n"
    "    const res = await GatewayAPI.removeDevice(g_deviceNameToDelete);\n"
    "    if (res.code === 0) {\n"
    "      showToast('✅ 设备 [' + g_deviceNameToDelete + '] 已成功移除并从 NVS 更新!', 'ok');\n"
    "      closeDeleteModal();\n"
    "      await loadAndRenderConfigTable();\n"
    "    } else {\n"
    "      showToast('❌ 删除失败: ' + res.message, 'err');\n"
    "    }\n"
    "  } catch (err) {\n"
    "    showToast('❌ 删除出错: ' + err.message, 'err');\n"
    "  }\n"
    "}\n"
    "\n"
    "// 10. 全局 Toast 提示\n"
    "function showToast(msg, type) {\n"
    "  const toast = document.getElementById('alert-toast');\n"
    "  if (!toast) return;\n"
    "  toast.textContent = msg;\n"
    "  toast.className = 'alert-toast active ' + (type === 'ok' ? 'badge-ok' : (type === 'warn' ? 'badge-warn' : 'badge-err'));\n"
    "  setTimeout(() => {\n"
    "    toast.classList.remove('active');\n"
    "  }, 4000);\n"
    "}\n"
    "\n"
    "window.loadAndRenderConfigTable = loadAndRenderConfigTable;\n"
    "window.openAddDeviceModal = openAddDeviceModal;\n"
    "window.openEditDeviceModal = openEditDeviceModal;\n"
    "window.closeDeviceModal = closeDeviceModal;\n"
    "window.onTestConfigClick = onTestConfigClick;\n"
    "window.onSaveConfigClick = onSaveConfigClick;\n"
    "window.openDeleteDeviceModal = openDeleteDeviceModal;\n"
    "window.closeDeleteModal = closeDeleteModal;\n"
    "window.onConfirmDeleteDevice = onConfirmDeleteDevice;\n"
    "window.showToast = showToast;\n"
    "";
static const char s_app_js[] = "﻿/**\n"
    " * ============================================================================\n"
    " * ESP32 工业网关主程序逻辑 (app.js)\n"
    " * 负责 SPA Tab 路由切换、实时遥测快照轮询、系统状态监控\n"
    " * ============================================================================\n"
    " */\n"
    "\n"
    "let g_activeTab = 'dashboard';\n"
    "let g_pollTimer = null;\n"
    "\n"
    "// 1. Tab 切换逻辑\n"
    "function switchTab(tabId) {\n"
    "  g_activeTab = tabId;\n"
    "  document.querySelectorAll('.tab-btn').forEach(btn => {\n"
    "    btn.classList.toggle('active', btn.dataset.tab === tabId);\n"
    "  });\n"
    "  document.querySelectorAll('.tab-panel').forEach(panel => {\n"
    "    panel.classList.toggle('active', panel.id === 'tab-' + tabId);\n"
    "  });\n"
    "\n"
    "  if (tabId === 'config') {\n"
    "    loadAndRenderConfigTable();\n"
    "  } else if (tabId === 'status') {\n"
    "    refreshSystemStatus();\n"
    "  } else if (tabId === 'dashboard') {\n"
    "    refreshTelemetrySnapshot();\n"
    "  }\n"
    "}\n"
    "\n"
    "// 2. 格式化运行时间 (秒 -> hh:mm:ss)\n"
    "function formatUptime(seconds) {\n"
    "  const h = Math.floor(seconds / 3600);\n"
    "  const m = Math.floor((seconds % 3600) / 60);\n"
    "  const s = seconds % 60;\n"
    "  return [h, m, s].map(v => v.toString().padStart(2, '0')).join(':');\n"
    "}\n"
    "\n"
    "// 3. 刷新系统状态 (Tab 3 与 Header 徽章)\n"
    "async function refreshSystemStatus() {\n"
    "  try {\n"
    "    const data = await GatewayAPI.getStatus();\n"
    "    \n"
    "    // 更新 Header 徽章\n"
    "    const wifiBadge = document.getElementById('header-wifi-badge');\n"
    "    if (wifiBadge) {\n"
    "      const isConnected = data.wifi_status === 'connected';\n"
    "      wifiBadge.className = 'badge ' + (isConnected ? 'badge-ok' : 'badge-err');\n"
    "      wifiBadge.textContent = 'WiFi: ' + (isConnected ? '已连接' : '离线');\n"
    "    }\n"
    "\n"
    "    const mqttBadge = document.getElementById('header-mqtt-badge');\n"
    "    if (mqttBadge) {\n"
    "      const isConnected = data.mqtt_status === 'connected';\n"
    "      mqttBadge.className = 'badge ' + (isConnected ? 'badge-ok' : 'badge-warn');\n"
    "      mqttBadge.textContent = 'MQTT: ' + (isConnected ? '在线' : '离线');\n"
    "    }\n"
    "\n"
    "    const uptimeBadge = document.getElementById('header-uptime-badge');\n"
    "    if (uptimeBadge) {\n"
    "      uptimeBadge.textContent = '运行: ' + formatUptime(data.uptime_sec || 0);\n"
    "    }\n"
    "\n"
    "    // 更新 Tab 3 系统状态卡片内容\n"
    "    const setVal = (id, val) => {\n"
    "      const el = document.getElementById(id);\n"
    "      if (el) el.textContent = val;\n"
    "    };\n"
    "\n"
    "    setVal('stat-gw-id', data.gateway_id || 'esp32_gateway_001');\n"
    "    setVal('stat-fw-ver', data.firmware_version || 'v1.0');\n"
    "    setVal('stat-cfg-ver', 'v' + (data.config_version || 1));\n"
    "    setVal('stat-uptime', formatUptime(data.uptime_sec || 0) + ' (' + data.uptime_sec + 's)');\n"
    "    \n"
    "    const freeHeapKb = Math.round((data.free_heap_bytes || 0) / 1024);\n"
    "    const minFreeHeapKb = Math.round((data.min_free_heap_bytes || 0) / 1024);\n"
    "    setVal('stat-heap', freeHeapKb + ' KB (最低: ' + minFreeHeapKb + ' KB)');\n"
    "    setVal('stat-wifi', data.wifi_status === 'connected' ? '🟢 已连接 (STA)' : '🔴 断开');\n"
    "    setVal('stat-mqtt', data.mqtt_status === 'connected' ? '🟢 已连接 (EMQX)' : '🟡 未就绪');\n"
    "  } catch (err) {\n"
    "    console.warn('获取系统状态失败:', err);\n"
    "  }\n"
    "}\n"
    "\n"
    "// 4. 刷新实时遥测与数字孪生快照 (Tab 1)\n"
    "async function refreshTelemetrySnapshot() {\n"
    "  const container = document.getElementById('telemetry-cards-container');\n"
    "  if (!container) return;\n"
    "\n"
    "  try {\n"
    "    const data = await GatewayAPI.getSnapshot();\n"
    "    const devices = data.devices || [];\n"
    "\n"
    "    if (devices.length === 0) {\n"
    "      container.innerHTML = '<div class=\\\"card\\\" style=\\\"grid-column:1/-1;text-align:center;color:var(--text-muted);padding:32px;\\\">当前没有活跃的采集设备，请切换至 [设备配置] 添加 Modbus 节点</div>';\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    let cardsHtml = '';\n"
    "    devices.forEach(dev => {\n"
    "      const isOnline = (dev.status === 0);\n"
    "      const statusBadge = isOnline \n"
    "        ? '<span class=\\\"badge badge-ok\\\">● 通信正常</span>'\n"
    "        : (dev.status === 1 ? '<span class=\\\"badge badge-err\\\">● 离线</span>' : '<span class=\\\"badge badge-warn\\\">● 通信超时</span>');\n"
    "\n"
    "      let metricsHtml = '';\n"
    "      const metrics = dev.metrics || [];\n"
    "      if (metrics.length === 0) {\n"
    "        metricsHtml = '<div class=\\\"metric-row\\\"><span class=\\\"metric-name\\\">测点数据</span><span class=\\\"metric-val\\\">--</span></div>';\n"
    "      } else {\n"
    "        metrics.forEach(m => {\n"
    "          const valStr = (typeof m.value === 'number') ? m.value.toFixed(2) : (m.value !== undefined ? m.value : '--');\n"
    "          const unitStr = m.unit || '';\n"
    "          metricsHtml += '<div class=\\\"metric-row\\\">' +\n"
    "            '<span class=\\\"metric-name\\\">' + m.name + '</span>' +\n"
    "            '<span class=\\\"metric-val\\\">' + valStr + ' ' + unitStr + '</span>' +\n"
    "          '</div>';\n"
    "        });\n"
    "      }\n"
    "\n"
    "      cardsHtml += '<div class=\\\"card\\\">' +\n"
    "        '<div class=\\\"card-header\\\">' +\n"
    "          '<h2>' + dev.name + ' <small style=\\\"font-size:12px;color:var(--text-muted);font-weight:normal;\\\">(从站: ' + dev.slave + ')</small></h2>' +\n"
    "          statusBadge +\n"
    "        '</div>' +\n"
    "        '<div class=\\\"card-body\\\">' +\n"
    "          metricsHtml +\n"
    "        '</div>' +\n"
    "      '</div>';\n"
    "    });\n"
    "\n"
    "    container.innerHTML = cardsHtml;\n"
    "  } catch (err) {\n"
    "    console.warn('获取遥测快照失败:', err);\n"
    "  }\n"
    "}\n"
    "\n"
    "// 5. 页面初始化\n"
    "document.addEventListener('DOMContentLoaded', () => {\n"
    "  // 绑定 Tab 按钮点击事件\n"
    "  document.querySelectorAll('.tab-btn').forEach(btn => {\n"
    "    btn.addEventListener('click', () => switchTab(btn.dataset.tab));\n"
    "  });\n"
    "\n"
    "  // 初始加载\n"
    "  refreshSystemStatus();\n"
    "  refreshTelemetrySnapshot();\n"
    "\n"
    "  // 启动后台定时轮询 (每 1.5 秒自动更新遥测与状态)\n"
    "  g_pollTimer = setInterval(() => {\n"
    "    refreshSystemStatus();\n"
    "    if (g_activeTab === 'dashboard') {\n"
    "      refreshTelemetrySnapshot();\n"
    "    }\n"
    "  }, 1500);\n"
    "});\n"
    "";

esp_err_t static_index_html_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    return httpd_resp_send(req, s_index_html, sizeof(s_index_html) - 1);
}

esp_err_t static_style_css_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/css; charset=utf-8");
    return httpd_resp_send(req, s_style_css, sizeof(s_style_css) - 1);
}

esp_err_t static_api_js_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "application/javascript; charset=utf-8");
    return httpd_resp_send(req, s_api_js, sizeof(s_api_js) - 1);
}

esp_err_t static_config_editor_js_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "application/javascript; charset=utf-8");
    return httpd_resp_send(req, s_config_editor_js, sizeof(s_config_editor_js) - 1);
}

esp_err_t static_app_js_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "application/javascript; charset=utf-8");
    return httpd_resp_send(req, s_app_js, sizeof(s_app_js) - 1);
}
